In [5]:
import pandas as pd
import numpy as np
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [7]:
data = pd.read_csv("fifa19.csv")
display(data)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [8]:
shape = data.shape
display(shape)

(18207, 89)

In [9]:
total_columns=data.columns
display(total_columns)

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [13]:
data.columns.shape

(89,)

In [15]:
# to get some specific columns 
some = data[["ID", "Name", "Age", "Preferred Foot", "Club", "Nationality"]]
some

,ID,Name,Age,Preferred Foot,Club,Nationality
0,158023,L. Messi,31,Left,FC Barcelona,Argentina
1,20801,Cristiano Ronaldo,33,Right,Juventus,Portugal
2,190871,Neymar Jr,26,Right,Paris Saint-Germain,Brazil
3,193080,De Gea,27,Right,Manchester United,Spain
4,192985,K. De Bruyne,27,Right,Manchester City,Belgium
...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,Right,Crewe Alexandra,England
18203,243165,N. Christoffersson,19,Right,Trelleborgs FF,Sweden
18204,241638,B. Worman,16,Right,Cambridge United,England
18205,246268,D. Walker-Rice,17,Right,Tranmere Rovers,England
18206,246269,G. Nugent,16,Right,Tranmere Rovers,England

In [16]:
#Lets remove Nationality using POP
some.pop("Nationality")
some

           ID                Name  Age Preferred Foot                 Club
0      158023            L. Messi   31           Left         FC Barcelona
1       20801   Cristiano Ronaldo   33          Right             Juventus
2      190871           Neymar Jr   26          Right  Paris Saint-Germain
3      193080              De Gea   27          Right    Manchester United
4      192985        K. De Bruyne   27          Right      Manchester City
...       ...                 ...  ...            ...                  ...
18202  238813        J. Lundstram   19          Right      Crewe Alexandra
18203  243165  N. Christoffersson   19          Right       Trelleborgs FF
18204  241638           B. Worman   16          Right     Cambridge United
18205  246268      D. Walker-Rice   17          Right      Tranmere Rovers
18206  246269           G. Nugent   16          Right      Tranmere Rovers

[18207 rows x 5 columns]

<ipython-input-24-231ef466b313>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  some["Players Hipe"] = some ["Age"].astype(str) + " " + some["Club"]

,ID,Name,Age,Preferred Foot,Club,Payers Hipe,Players Hipe,Hipe
0,158023,L. Messi,31,Left,FC Barcelona,31 FC Barcelona,31 FC Barcelona,31 FC Barcelona
1,20801,Cristiano Ronaldo,33,Right,Juventus,33 Juventus,33 Juventus,33 Juventus
2,190871,Neymar Jr,26,Right,Paris Saint-Germain,26 Paris Saint-Germain,26 Paris Saint-Germain,26 Paris Saint-Germain
3,193080,De Gea,27,Right,Manchester United,27 Manchester United,27 Manchester United,27 Manchester United
4,192985,K. De Bruyne,27,Right,Manchester City,27 Manchester City,27 Manchester City,27 Manchester City
...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,Right,Crewe Alexandra,19 Crewe Alexandra,19 Crewe Alexandra,19 Crewe Alexandra
18203,243165,N. Christoffersson,19,Right,Trelleborgs FF,19 Trelleborgs FF,19 Trelleborgs FF,19 Trelleborgs FF
18204,241638,B. Worman,16,Right,Cambridge United,16 Cambridge United,16 Cambridge United,16 Cambridge United
18205,246268,D. Walker-Rice,17,Right,Tranmere Rovers,17 Tranmere Rovers,17 Tranmere Rovers,17 Tranmere Rovers
18206,246269,G. Nugent,16,Right,Tranmere Rovers,16 Tranmere Rovers,16 Tranmere Rovers,16 Tranmere Rovers

In [25]:
#Get for a specific country..Nigeria
def country(x):
    return data[data["Nationality"]==x][["Name", 'Potential', "Overall", "Position"]]
country("Nigeria")

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [26]:
some["Players Hipe"] = some ["Age"].astype(str) + " " + some["Club"]
some

<ipython-input-26-231ef466b313>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  some["Players Hipe"] = some ["Age"].astype(str) + " " + some["Club"]

,ID,Name,Age,Preferred Foot,Club,Payers Hipe,Players Hipe,Hipe
0,158023,L. Messi,31,Left,FC Barcelona,31 FC Barcelona,31 FC Barcelona,31 FC Barcelona
1,20801,Cristiano Ronaldo,33,Right,Juventus,33 Juventus,33 Juventus,33 Juventus
2,190871,Neymar Jr,26,Right,Paris Saint-Germain,26 Paris Saint-Germain,26 Paris Saint-Germain,26 Paris Saint-Germain
3,193080,De Gea,27,Right,Manchester United,27 Manchester United,27 Manchester United,27 Manchester United
4,192985,K. De Bruyne,27,Right,Manchester City,27 Manchester City,27 Manchester City,27 Manchester City
...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,Right,Crewe Alexandra,19 Crewe Alexandra,19 Crewe Alexandra,19 Crewe Alexandra
18203,243165,N. Christoffersson,19,Right,Trelleborgs FF,19 Trelleborgs FF,19 Trelleborgs FF,19 Trelleborgs FF
18204,241638,B. Worman,16,Right,Cambridge United,16 Cambridge United,16 Cambridge United,16 Cambridge United
18205,246268,D. Walker-Rice,17,Right,Tranmere Rovers,17 Tranmere Rovers,17 Tranmere Rovers,17 Tranmere Rovers
18206,246269,G. Nugent,16,Right,Tranmere Rovers,16 Tranmere Rovers,16 Tranmere Rovers,16 Tranmere Rovers

In [28]:
some["Players Hipe"]'= some ["Age"].astype(str) + " " + some["Club"]
some

SyntaxError: EOL while scanning string literal (<ipython-input-28-b5446a926041>, line 1)

In [14]:
data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [6]:
#Get for a specific country..Nigeria
def country(x):
    return data[data["Nationality"]==x][["Name", 'Potential', "Overall", "Position"]]
country("Nigeria")

              Name  Potential  Overall Position
425       W. Ndidi         85       80      LDM
789       A. Iwobi         84       78       LM
858       V. Moses         78       78       RW
1022     O. Ighalo         77       77       ST
1296   H. Onyekuru         86       76       ST
...            ...        ...      ...      ...
17096    J. Kayode         70       55       ST
17160     H. Offia         66       55       LM
17261    R. Ayagwa         67       55       CM
17652     A. Yusuf         69       53       CM
18174   S. Adewusi         63       48       CM

[121 rows x 4 columns]

In [7]:
#Get club FC Barcelonia
def club(x):
    return data[data["Club"]==x][["Name", 'Nationality', "Overall", "Position", "Age", "Jersey Number", "Wage", "Release Clause"]]
club("FC Barcelona")

,Name,Nationality,Overall,Position,Age,Jersey Number,Wage,Release Clause
0,L. Messi,Argentina,94,RF,31,10.0,€565K,€226.5M
7,L. Suárez,Uruguay,91,RS,31,9.0,€455K,€164M
18,M. ter Stegen,Germany,89,GK,26,22.0,€240K,€123.3M
20,Sergio Busquets,Spain,89,CDM,29,5.0,€315K,€105.6M
32,Coutinho,Brazil,88,LW,26,7.0,€340K,€147.7M
42,S. Umtiti,France,87,CB,24,23.0,€205K,€121.1M
49,Jordi Alba,Spain,87,LB,29,18.0,€250K,€77.9M
53,I. Rakitić,Croatia,87,RCM,30,4.0,€260K,€95.3M
54,Piqué,Spain,87,RCB,31,3.0,€240K,€69.7M
96,A. Vidal,Chile,85,CAM,31,8.0,€205K,€53.3M
155,O. Dembélé,France,83,RW,21,11.0,€155K,€90M
192,Sergi Roberto,Spain,83,RB,26,20.0,€170K,€56.3M
228,Arthur,Brazil,82,LCM,21,8.0,€125K,€73.1M
236,Malcom,Brazil,82,RW,21,14.0,€140K,€70.9M
239,C. Lenglet,France,82,LCB,23,15.0,€135K,€58.5M
263,Rafinha,Brazil,82,CAM,25,12.0,€165K,€62.7M
266,J. Cillessen,Netherlands,82,GK,29,1.0,€135K,€38.3M
324,Nélson Semedo,Portugal,81,RB,24,2.0,€125K,€42.5M
613,Denis Suárez,Spain,79,CM,24,6.0,€120K,€39.4M
1007,Munir,Spain,77,ST,22,19.0,€115K,€28.1M
1037,T. Vermaelen,Belgium,77,CB,32,3.0,€110K,€10.3M
3118,Sergi Samper,Spain,73,CDM,23,16.0,€69K,€10.8M
3684,Aleñá,Spain,72,CM,20,21.0,€58K,€16.1M
6000,M. Wagué,Senegal,69,RB,19,37.0,€20K,€3.6M
6102,Riqui Puig,Spain,69,CM,18,28.0,€24K,€6.5M
8284,Oriol Busquets,Spain,67,CDM,19,35.0,€14K,€4M
8289,Abel Ruiz,Spain,67,ST,18,29.0,€21K,€4.2M
8857,Miranda,Spain,66,LB,18,27.0,€12K,€3.2M
10526,Chumi,Spain,65,CB,19,36.0,€11K,€2.8M
10777,Jorge Cuenca,Spain,65,CB,18,33.0,€11K,€2.3M
11300,Guillem Jaime,Spain,64,RW,19,38.0,€13K,€2.6M
12502,Ezkieta,Spain,63,GK,21,31.0,€10K,€1.2M
14286,Iñaki Peña,Spain,61,GK,19,30.0,€4K,€1.2M

In [8]:
club("Manchester United").count()

Name              33
Nationality       33
Overall           33
Position          33
Age               33
Jersey Number     33
Wage              33
Release Clause    33
dtype: int64

In [9]:
data.isnull().sum()

Unnamed: 0           0
ID                   0
Name                 0
Age                  0
Photo                0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 89, dtype: int64

In [10]:
#To replace GKHandling null values with mean
y = round(data['GKHandling'].mean())
y

16

In [11]:
z =data['GKHandling'].fillna(y, inplace = True)
data['GKHandling']

0        11.0
1        11.0
2         9.0
3        85.0
4        13.0
         ...
18202    13.0
18203     9.0
18204     5.0
18205     6.0
18206    15.0
Name: GKHandling, Length: 18207, dtype: float64

In [12]:
data["GKHandling"].isnull()
#Done.. no null values

0        False
1        False
2        False
3        False
4        False
         ...
18202    False
18203    False
18204    False
18205    False
18206    False
Name: GKHandling, Length: 18207, dtype: bool

In [13]:
gh = data.describe()
gh

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18207.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.390564,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.884610,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [16]:
data = pd.read_csv("fifa19.csv")
display(data)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K